# Generated by Django 5.2.9 on 2026-03-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
