# Generated by Django 6.0.2 on 2026-03-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forncedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
