# Generated by Django 5.2.9 on 2026-03-17 11:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forncedores', '0002_alter_fornecedor_estado'),
        ('produtos', '0004_alter_produto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da compra')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='compras.compra')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forncedores.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'A quantidade deve ser maior ou igual a 1')], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'O preço unitário deve ser maior que zero')])),
                ('compra_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.comprafornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comprafornecedor',
            constraint=models.UniqueConstraint(fields=('compra', 'fornecedor'), name='uniq_compra_fornecedor_grupo'),
        ),
        migrations.AddConstraint(
            model_name='itemcompra',
            constraint=models.UniqueConstraint(fields=('compra_fornecedor', 'produto'), name='uniq_item_por_produto_no_fornecedor'),
        ),
    ]
