# Generated by Django 6.0.2 on 2026-03-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_id_alter_comprafornecedor_id_and_more'),
        ('forncedores', '0003_fornecedor_agencia_fornecedor_bairro_and_more'),
        ('produtos', '0005_remove_produto_preco_produto_ativo_produto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comprafornecedor',
            name='uniq_compra_fornecedor_grupo',
        ),
        migrations.RemoveConstraint(
            model_name='itemcompra',
            name='uniq_item_por_produto_no_fornecedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forncedores.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.compra'),
        ),
        migrations.AddConstraint(
            model_name='itemcompra',
            constraint=models.UniqueConstraint(fields=('compra', 'produto'), name='uniq_item_por_produto_na_compra'),
        ),
        migrations.RemoveField(
            model_name='itemcompra',
            name='compra_fornecedor',
        ),
        migrations.DeleteModel(
            name='CompraFornecedor',
        ),
    ]
