# Generated by Django 6.0.2 on 2026-03-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_comprafornecedor_uniq_compra_fornecedor_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADA', 'Confirmada'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20),
        ),
    ]
